version: '3'
services:
  peopleservice-people-database:
    image: postgres:9.5
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=people
    command: ["-p", "54321"]
    ports:
    - "54321:54321"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:5.0.5
    ports:
      - '6379:6379'
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis-data:/data

volumes:
  pgdata:
    external: true