spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: jianglianein
    password: ft1998226
    url: jdbc:postgresql://34.85.125.49:5432/people
  application:
    name: people-service-API
  redis:
    host: 34.85.125.49
    port: 6379
    timeout: 10000
cors:
  url: "*"

env: "dev"
