spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:54321/people
  application:
    name: people-service-API
  redis:
    host: localhost
    port: 6379
    timeout: 10000
  mail:
    host: smtp.qq.com
    username: 913057041@qq.com
    password: vcxnmszkmxodbefj
    default-encoding: utf-8
    properties:
      mail:
        auth: true
        starttls:
          enable: true
          required: true
cors:
  url: "*"

microservice:
  peopleservice:
    url: http://localhost:8000

env: "local"

server:
  #端口号
  port: 8000
#  address: 10.144.78.161