spring:
  datasource:
    driver-class-name:
    username:
    password:
    url:
  application:
    name: people-service-API
  redis:
    host:
    port:
    timeout: 10000
    password:
  mail:
    host:
    username:
    password:
    default-encoding:
    properties:
      mail:
        auth: true
        starttls:
          enable: true
          required: true
cors:
  url:

microservice:
  peopleservice:
    url:

env: "dev"

server:
  port:
