spring:
  profiles:
    active: dev
  mail:
    host: smtp.qq.com
    username: 913057041@qq.com
    password: vcxnmszkmxodbefj
    default-encoding: utf-8
    properties:
      mail:
        auth: true
        starttls:
          enable: true
          required: true

