spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:54321/user
  application:
    name: people-service-API
cors:
  url: "*"

env: "local"