spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: jianglianein
    password: ft1998226
    url: jdbc:postgresql://45.32.133.122:5432/people
  application:
    name: people-service-API
  redis:
    host: 45.32.133.122
    port: 6379
    timeout: 10000
cors:
  url: "*"

env: "dev"

server:
  #端口号
  port: 8000
