apiVersion: apps/v1
kind: Deployment
metadata:
  name: peopleservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: peopleservice-deployment
  template:
    metadata:
      labels:
        app: peopleservice-deployment
    spec:
      containers:
      - name: peopleservice-deployment
        image: ${IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
